import { describe, expect, it } from "vitest";
import {
  DIRECTX_PARSE_LIMITS,
  parseDirectX,
} from "../src/renderer/engine/directx";

const I = "1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1";
const triangle = "3; 0;0;0;,1;0;0;,0;1;0;; 1;3;0,1,2;;";
const x = (body: string) => `xof 0303txt 0032\n${body}`;
const mesh = (body = "", data = triangle) => `Mesh Mark {${data} ${body}}`;
const skin = (bone: string, weights = "1,1,1", indices = "0,1,2", offset = I) =>
  `SkinWeights {"${bone}";3;${indices};${weights};${offset};;}`;

/** This independent test encoder writes Microsoft's documented primitive tokens,
 * not bytes generated by the production text lexer or parser. */
function binary(floatBits: 32 | 64, stringWord = false, flags?: number) {
  const chunks: Uint8Array[] = [
    new TextEncoder().encode(`xof 0303bin 00${floatBits}`),
  ];
  const u16 = (value: number) => {
    const b = new Uint8Array(2);
    new DataView(b.buffer).setUint16(0, value, true);
    chunks.push(b);
  };
  const u32 = (value: number) => {
    const b = new Uint8Array(4);
    new DataView(b.buffer).setUint32(0, value, true);
    chunks.push(b);
  };
  const text = (value: string, token = 1) => {
    u16(token);
    const b = new TextEncoder().encode(value);
    u32(b.length);
    chunks.push(b);
    if (token === 2) stringWord ? u16(20) : u32(20);
  };
  const integers = (...values: number[]) => {
    u16(6);
    u32(values.length);
    values.forEach(u32);
  };
  const floats = (...values: number[]) => {
    u16(7);
    u32(values.length);
    const b = new Uint8Array((values.length * floatBits) / 8),
      v = new DataView(b.buffer);
    values.forEach((n, i) =>
      floatBits === 32
        ? v.setFloat32(i * 4, n, true)
        : v.setFloat64(i * 8, n, true),
    );
    chunks.push(b);
  };
  const open = (type: string) => {
    text(type);
    u16(10);
  };
  if (flags !== undefined) {
    open("Header");
    integers(1, 0, flags);
    u16(11);
  }
  open("Mesh");
  integers(3);
  floats(0, 0, 0, 1, 0, 0, 0, 1, 0);
  integers(1, 3, 0, 1, 2);
  open("MeshMaterialList");
  integers(1, 1, 0);
  open("Material");
  floats(1, 0.5, 0.25, 1, 7, 0.2, 0.3, 0.4, 0, 0, 0);
  open("TextureFilename");
  text("original.png", 2);
  u16(11);
  u16(11);
  u16(11);
  u16(11);
  const out = new Uint8Array(chunks.reduce((n, b) => n + b.length, 0));
  let at = 0;
  for (const b of chunks) {
    out.set(b, at);
    at += b.length;
  }
  return out;
}

describe("independent bounded DirectX geometry reader", () => {
  it("preserves source units and row-vector matrices without GPU allocation", () => {
    const result = parseDirectX(
      x(
        `Frame root {FrameTransformMatrix {1,0,0,0,0,1,0,0,0,0,1,0,3,4,5,1;;} Frame child {${mesh()}}}`,
      ),
    );
    expect(result).toMatchObject({
      format: "x",
      encoding: "text",
      version: "0303",
      floatBits: 32,
      hasEmbeddedAnimation: false,
      warnings: [],
    });
    expect(result.frames.map((f) => [f.id, f.parent, f.name])).toEqual([
      [0, null, "root"],
      [1, 0, "child"],
    ]);
    expect(result.frames[0].matrix.slice(12, 15)).toEqual([3, 4, 5]);
    expect(result.meshes[0].positions).toEqual([0, 0, 0, 1, 0, 0, 0, 1, 0]);
    expect(result.meshes[0]).toMatchObject({
      frame: 1,
      faces: [[0, 1, 2]],
      materialIndices: [0],
      skinWeights: [],
    });
  });
  it("handles comments, custom templates and object UUIDs without executing them", () => {
    const result = parseDirectX(
      x(`template Custom { < 12345678-1234-1234-1234-123456789abc > DWORD a; [...] }
      # } fake frame
      // Mesh unsafe {
      /* { } */ Mesh {<12345678-1234-1234-1234-123456789abc> ${triangle}} Custom { 2; Nested {"}";} }`),
    );
    expect(result.meshes).toHaveLength(1);
    expect(result.warnings).toEqual(["Unsupported X template: Custom"]);
  });
  it("preserves independent normal indices, vertex UVs and indexed RGBA", () => {
    const result = parseDirectX(
      x(
        mesh(`MeshNormals {2;0;0;1;,0;0;-1;;1;3;1,0,1;;}
      MeshTextureCoords {3;0;0;,1;0;,0;1;;} MeshVertexColors {1;1;0.2;0.3;0.4;0.5;;;}`),
      ),
    ).meshes[0];
    expect(result.normalFaces).toEqual([[1, 0, 1]]);
    expect(result.normals).toEqual([0, 0, 1, 0, 0, -1]);
    expect(result.uvs).toEqual([0, 0, 1, 0, 0, 1]);
    expect(result.colors).toEqual([1, 1, 1, 1, 0.2, 0.3, 0.4, 0.5, 1, 1, 1, 1]);
  });
  it("resolves forward material references without changing filename case", () => {
    const result = parseDirectX(
      x(
        `${mesh("MeshMaterialList {1;1;0;{Ocean}}")} Material Ocean {0;0.5;1;0.6;;12;1;1;1;;0;0;0;;TextureFilename {"Color.png";}}`,
      ),
    );
    expect(result.meshes[0].materials[0]).toMatchObject({
      name: "Ocean",
      diffuse: [0, 0.5, 1, 0.6],
      power: 12,
      texture: "Color.png",
    });
  });
  it.each([
    "<11223344-1234-5678-9abc-123456789abc>",
    "Ocean <11223344-1234-5678-9abc-123456789abc>",
  ])("resolves material reference %s using UUID identity", (ref) => {
    const material =
      "Material Ocean {<11223344-1234-5678-9abc-123456789abc> 0;0.5;1;1;;0;0;0;0;;0;0;0;;}";
    expect(
      parseDirectX(x(`${material}${mesh(`MeshMaterialList {1;1;0;{${ref}}}`)}`))
        .meshes[0].materials[0].name,
    ).toBe("Ocean");
  });
  it("rejects material references whose name and UUID identify different objects", () => {
    const materials =
      "Material One {<11223344-1234-5678-9abc-123456789abc> 1;1;1;1;;0;0;0;0;;0;0;0;;} Material Two {1;1;1;1;;0;0;0;0;;0;0;0;;}";
    expect(() =>
      parseDirectX(
        x(
          `${materials}${mesh("MeshMaterialList {1;1;0;{Two <11223344-1234-5678-9abc-123456789abc>}}")}`,
        ),
      ),
    ).toThrow(/mismatch/);
  });
  it.each([32, 64] as const)(
    "reads binary %i-bit numeric lists and DWORD string terminators",
    (bits) => {
      const result = parseDirectX(binary(bits));
      expect(result).toMatchObject({ encoding: "binary", floatBits: bits });
      expect(result.meshes[0].positions).toEqual([0, 0, 0, 1, 0, 0, 0, 1, 0]);
      expect(result.meshes[0].materials[0]).toMatchObject({
        texture: "original.png",
        power: 7,
      });
    },
  );
  it("accepts distinguishable WORD string terminators used by exporters", () => {
    expect(parseDirectX(binary(32, true)).meshes[0].materials[0].texture).toBe(
      "original.png",
    );
  });
  it("resolves an independently encoded binary UUID material reference", () => {
    const source = Buffer.from(binary(32));
    const materialToken = Buffer.from([
      1,
      0,
      8,
      0,
      0,
      0,
      ...new TextEncoder().encode("Material"),
      10,
      0,
    ]);
    const at = source.indexOf(materialToken);
    expect(at).toBeGreaterThan(16);
    // UUID 11223344-5566-7788-99aa-bbccddeeff00 has mixed DWORD/WORD
    // little-endian fields, followed by eight literal octets.
    const uuid = Buffer.from([
      5, 0, 0x44, 0x33, 0x22, 0x11, 0x66, 0x55, 0x88, 0x77, 0x99, 0xaa, 0xbb,
      0xcc, 0xdd, 0xee, 0xff, 0x00,
    ]);
    const definition = Buffer.concat([
      source.subarray(0, at + materialToken.length),
      uuid,
      source.subarray(at + materialToken.length),
    ]);
    const reference = Buffer.concat([
      source.subarray(16, at),
      Buffer.from([10, 0]),
      uuid,
      Buffer.from([11, 0, 11, 0, 11, 0]),
    ]);
    const result = parseDirectX(Buffer.concat([definition, reference]));
    expect(result.meshes).toHaveLength(2);
    expect(result.meshes[1].materials[0]).toBe(result.meshes[0].materials[0]);
    const mismatched = Buffer.from(reference);
    mismatched[reference.length - 7] ^= 1;
    expect(() => parseDirectX(Buffer.concat([definition, mismatched]))).toThrow(
      /unresolved material/,
    );
  });
  it("accepts same-mode Header flags and refuses mixed-mode or unknown flags", () => {
    expect(parseDirectX(x(`Header {1;0;1;}${mesh()}`)).meshes).toHaveLength(1);
    expect(parseDirectX(binary(32, false, 0)).meshes).toHaveLength(1);
    expect(() => parseDirectX(x(`Header {1;0;0;}${mesh()}`))).toThrow(
      /mixed-mode/,
    );
    expect(() => parseDirectX(binary(32, false, 1))).toThrow(/mixed-mode/);
    expect(() => parseDirectX(binary(32, false, 2))).toThrow(
      /unknown Header flags/,
    );
  });
  it("keeps exact blended skin weights and offset matrices", () => {
    const result = parseDirectX(
      x(
        `Frame aw_pelvis {Frame aw_lfelbow {}} ${mesh(`XSkinMeshHeader {2;2;2;} ${skin("aw_pelvis", "1,0.25,0.5")} ${skin("aw_lfelbow", "0,0.75,0.5")}`)}`,
      ),
    );
    expect(result.meshes[0].skinWeights.map((w) => w.weights)).toEqual([
      [1, 0.25, 0.5],
      [0, 0.75, 0.5],
    ]);
    expect(result.meshes[0].skinWeights[0].offsetMatrix).toEqual(
      I.split(",").map(Number),
    );
  });
  it("reports embedded animations without inventing playback or motion", () => {
    const result = parseDirectX(
      x(
        `${mesh()} AnimTicksPerSecond {30;} AnimationSet Walk { Animation { {joint} AnimationKey {0;0;} } }`,
      ),
    );
    expect(result.hasEmbeddedAnimation).toBe(true);
    expect(result.warnings).toEqual([expect.stringContaining("not played")]);
  });
  it.each(["tzip", "bzip"])(
    "rejects malformed compressed %s size headers before allocation",
    (encoding) => {
      expect(() => parseDirectX(`xof 0303${encoding}0032payload`)).toThrow(
        /MSZIP.*invalid expanded file size/,
      );
    },
  );
  it('keeps the separately unsupported legacy cmp encoding explicit', () => {
    expect(() => parseDirectX('xof 0303cmp 0032payload')).toThrow(/legacy cmp encoding is not supported/);
  });
  it.each([
    ["negative count", x(mesh("", "-1;")), /vertex/],
    ["huge count", x(mesh("", "999999999;")), /vertex/],
    ["excessive face", x(mesh("", "0;1;999999;")), /face/],
    [
      "bad vertex index",
      x(mesh("", triangle.replace("0,1,2", "0,1,3"))),
      /vertex/,
    ],
    ["missing number", x(mesh("", "3;0;0;}")), /number/],
    ["nonfinite float", x(mesh("", "3;1e999;")), /numeric/],
    ["garbage float", x(mesh("", "3;1abc;")), /numeric/],
    ["unclosed frame", x("Frame root {"), /unclosed/],
    ["extra close", x("}"), /closing/],
    ["unterminated comment", x("/*"), /comment/],
    ["unsupported declaration", x(mesh("DeclData {0;}")), /DeclData/],
    [
      "unresolved material",
      x(mesh("MeshMaterialList {1;1;0;{missing}}")),
      /unresolved material/,
    ],
    [
      "material count mismatch",
      x(mesh("MeshMaterialList {1;0;Material {1;1;1;1;;0;0;0;0;;0;0;0;;}}")),
      /face count/,
    ],
    ["UV mismatch", x(mesh("MeshTextureCoords {1;0;0;;}")), /UV count/],
    [
      "normal face mismatch",
      x(mesh("MeshNormals {1;0;0;1;;0;}")),
      /normal face count/,
    ],
    ["bad color", x(mesh("MeshVertexColors {1;0;2;0;0;1;;; }")), /color/],
    ["missing bone", x(mesh(skin("absent"))), /missing or ambiguous/],
    [
      "ambiguous bone",
      x(`Frame joint {} Frame joint {} ${mesh(skin("joint"))}`),
      /ambiguous/,
    ],
    [
      "negative weight",
      x(`Frame joint {} ${mesh(skin("joint", "1,-1,1"))}`),
      /skin weight/,
    ],
    [
      "incomplete weights",
      x(`Frame joint {} ${mesh(skin("joint", "1,0.5,1"))}`),
      /sum to one/,
    ],
    [
      "duplicate weights",
      x(`Frame joint {} ${mesh(skin("joint", "1,1,1", "0,0,2"))}`),
      /duplicate skin vertex/,
    ],
    [
      "singular offset",
      x(
        `Frame joint {} ${mesh(skin("joint", "1,1,1", "0,1,2", I.replace(/^1/, "0")))}`,
      ),
      /singular/,
    ],
    [
      "projective frame",
      x(
        `Frame root {FrameTransformMatrix {1,0,0,2,0,1,0,0,0,0,1,0,0,0,0,1;;}}`,
      ),
      /affine/,
    ],
  ])("rejects %s", (_name, source, match) => {
    expect(() => parseDirectX(source as string)).toThrow(match as RegExp);
  });
  it("rejects skin influences beyond the GPU contract instead of truncating", () => {
    const bones = Array.from({ length: 5 }, (_, i) => `j${i}`);
    expect(() =>
      parseDirectX(
        x(
          `${bones.map((b) => `Frame ${b} {}`).join("")} ${mesh(bones.map((b) => skin(b, "0.2,0.2,0.2")).join(""))}`,
        ),
      ),
    ).toThrow(/four positive/);
  });
  it("bounds empty bone declarations independently of influence and numeric counts", () => {
    const declarations = Array.from(
      { length: DIRECTX_PARSE_LIMITS.skinBones + 1 },
      (_, i) => `SkinWeights {"unused${i}";0;;;${I};;}`,
    ).join("");
    expect(() => parseDirectX(x(mesh(declarations)))).toThrow(
      /skin bone declaration budget/,
    );
  });
  it("bounds skipped metadata tokens independently of emitted geometry", () => {
    expect(() =>
      parseDirectX(x(`Unknown {${";".repeat(DIRECTX_PARSE_LIMITS.tokens)}}`)),
    ).toThrow(/token budget/);
  });
  it("counts empty binary numeric lists even though they emit no scalar tokens", () => {
    const bytes = new Uint8Array(16 + (DIRECTX_PARSE_LIMITS.tokens + 1) * 6);
    bytes.set(new TextEncoder().encode("xof 0303bin 0032"));
    for (let at = 16; at < bytes.length; at += 6) bytes[at] = 6;
    expect(() => parseDirectX(bytes)).toThrow(/binary record budget/);
  });
  it("rejects every truncated binary prefix without returning a partial model", () => {
    const bytes = binary(64);
    // Exactly the header is a valid empty X container, as are intentionally
    // empty numeric lists. Every later cut here leaves the mesh unclosed.
    for (let i = 17; i < bytes.length; i++)
      expect(() => parseDirectX(bytes.subarray(0, i)), `cut ${i}`).toThrow();
  });
  it("bounds both known and skipped nesting", () => {
    expect(() =>
      parseDirectX(
        x(
          "Frame f {".repeat(DIRECTX_PARSE_LIMITS.depth + 1) +
            "}".repeat(DIRECTX_PARSE_LIMITS.depth + 1),
        ),
      ),
    ).toThrow(/nesting/);
    expect(() =>
      parseDirectX(
        x(
          "Unknown {".repeat(DIRECTX_PARSE_LIMITS.depth + 2) +
            "}".repeat(DIRECTX_PARSE_LIMITS.depth + 2),
        ),
      ),
    ).toThrow(/nesting/);
  });
  it("rejects oversize bytes and malformed versions before tokenization", () => {
    expect(() =>
      parseDirectX(new Uint8Array(DIRECTX_PARSE_LIMITS.bytes + 1)),
    ).toThrow(/30 MB/);
    expect(() => parseDirectX(x(mesh()).replace("0303", "9999"))).toThrow(
      /header/,
    );
  });
});
